Avoid failure due to download timeout.
Info: Applying configuration version '1415787370'
Notice: Downloading
http://s3.amazonaws.com/influxdb/influxdb_0.8.4_amd64.deb
Notice: /Stage[main]/Influxdb::Install/Notify[Downloading
http://s3.amazonaws.com/influxdb/influxdb_0.8.4_amd64.deb]/message:
defined 'message' as 'Downloading
http://s3.amazonaws.com/influxdb/influxdb_0.8.4_amd64.deb'
Notice:
/Stage[main]/Influxdb::Install/Staging::File[influxdb-package]/File[/opt/staging/influxdb]/ensure:
created
Error: Command exceeded timeout
Error:
/Stage[main]/Influxdb::Install/Staging::File[influxdb-package]/Exec[/opt/staging/influxdb/influxdb-package]/returns:
change from notrun to 0 failed: Command exceeded timeout
Notice: /Stage[main]/Influxdb::Install/Package[influxdb]: Dependency
Exec[/opt/staging/influxdb/influxdb-package] has failures: true
Warning: /Stage[main]/Influxdb::Install/Package[influxdb]: Skipping
because of failed dependencies